apiVersion: v1
kind: ServiceAccount
metadata:
  name: retrain-sa
  namespace: automl-brain

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: retrain-role
  namespace: automl-brain
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: retrain-binding
  namespace: automl-brain
subjects:
- kind: ServiceAccount
  name: retrain-sa
roleRef:
  kind: Role
  name: retrain-role
  apiGroup: rbac.authorization.k8s.io