apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: inference-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: churn-inference
  namespaceSelector:
    matchNames:
      - automl-brain
  endpoints:
  - port: http
    path: /metrics
    interval: 15s