# 

apiVersion: v1
kind: Service
metadata:
  name: inference-service
  namespace: automl-brain
spec:
  type: ClusterIP
  selector:
    app: churn-inference
    track: stable
  ports:
  - port: 80
    targetPort: 8000