apiVersion: v1
kind: Service
metadata:
  name: inference-service
  namespace: automl-brain
  labels:
    app: churn-inference   # ðŸ”¥ REQUIRED for ServiceMonitor
spec:
  type: ClusterIP
  selector:
    app: churn-inference
  ports:
  - name: http
    port: 80
    targetPort: 8000