apiVersion: batch/v1
kind: Job
metadata:
  name: retrain-job
  namespace: automl-brain
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: retrain-sa
      restartPolicy: Never
      containers:
        - name: retraining
          image: 199964507152.dkr.ecr.us-east-1.amazonaws.com/automl-brain-training:latest
          imagePullPolicy: Always
          env:
            - name: AWS_REGION
              value: "us-east-1"